// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Ef-cOCrh9NfNBKlLTaTKI1edXOo38g4',
    appId: '1:676027575040:web:6d0928b96be79deb0ae1e5',
    messagingSenderId: '676027575040',
    projectId: 'biwah-bandhan-af0f6',
    authDomain: 'biwah-bandhan-af0f6.firebaseapp.com',
    storageBucket: 'biwah-bandhan-af0f6.appspot.com',
    measurementId: 'G-LFLKFF466P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDFSKaWDeLbq_Vu7dPevlx96PZSPh7gzk',
    appId: '1:676027575040:android:a29b70a79417f6840ae1e5',
    messagingSenderId: '676027575040',
    projectId: 'biwah-bandhan-af0f6',
    storageBucket: 'biwah-bandhan-af0f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQFJ6b7gHR32lewZKdWevociz5jHaLzww',
    appId: '1:676027575040:ios:93badc06696f48e90ae1e5',
    messagingSenderId: '676027575040',
    projectId: 'biwah-bandhan-af0f6',
    storageBucket: 'biwah-bandhan-af0f6.appspot.com',
    iosBundleId: 'com.example.biwah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQFJ6b7gHR32lewZKdWevociz5jHaLzww',
    appId: '1:676027575040:ios:93badc06696f48e90ae1e5',
    messagingSenderId: '676027575040',
    projectId: 'biwah-bandhan-af0f6',
    storageBucket: 'biwah-bandhan-af0f6.appspot.com',
    iosBundleId: 'com.example.biwah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Ef-cOCrh9NfNBKlLTaTKI1edXOo38g4',
    appId: '1:676027575040:web:c5ab33004b00d0e00ae1e5',
    messagingSenderId: '676027575040',
    projectId: 'biwah-bandhan-af0f6',
    authDomain: 'biwah-bandhan-af0f6.firebaseapp.com',
    storageBucket: 'biwah-bandhan-af0f6.appspot.com',
    measurementId: 'G-7EPKF6RNSL',
  );
}
